### ISSUE TITLE
Possible notification system bug (android.app.RemoteServiceException: can't deliver broadcast)

### ISSUE THREAD

**Issue by NeoTheFox** [ResurrectionRemix/android_frameworks_base#144]
I've recently opened a [bug](https://github.com/nextcloud/android/issues/413) on NextCloud client, and @AndyScherzinger suggested it might be a Resurrection Remix bug, so I am opening this too, just in case.
The problem: on startup of NextCloud beta client it crashes with this log:

```
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: can't deliver broadcast
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6095)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
This happens only on Resurrection Remix for me. [This is my version](http://forum.xda-developers.com/redmi-note-3/development/rom-resurrectionremix-5-8-0-t3507433).

**Comment by varund7726** [comment]
not a bug in RR but in cm14.1 due to zygote patches
